version: "3"

services:
  stagit:
    image: ghcr.io/tarneaux/stagit:latest

    restart: unless-stopped

    ports:
      - "8080:80"

    volumes:
      # The directory where your repositories are stored
      - ./repos:/repos
      - ./config:/config

    environment:
      BASEURL: http://localhost:8080
      OWNER: "Your Name"
      REMOTE: "https://your.git.server"
